main: us.fihgu.easyinventory.Loader
name: EasyInventory
version: 1.0.3
author: fihgu
description: helps people to manage their inventory
permissions:
 us.fihgu.easyinventory.sort:
  default: true
 us.fihgu.easyinventory.refill:
  default: true